name: Run tests and create coverage report
on: ["push", "pull_request"]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [20]
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: npm ci
      run: npm ci

    - name: "Run tests"
      run: npm run test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: ${{matrix.os}}-node-${{ matrix.node }}
        parallel: true

  finish:
    if: ${{ always() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
